spring:
#  config:
#    import: application-local.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${/spring-boot-aws/seb-006/spring.datasource.url}
    username: ${/spring-boot-aws/seb-006/spring.datasource.username}
    password: ${/spring-boot-aws/seb-006/spring.datasource.password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

cloud:
  aws:
    region:
      static: ${/spring-boot-aws/seb-006/cloud.aws.region.static}
    stack:
      auto: false
    credentials:
      access-key: ${/spring-boot-aws/seb-006/cloud.aws.credentials.access-key}
      secret-key: ${/spring-boot-aws/seb-006/cloud.aws.credentials.secret-key}